name: dm-cyt-tp2
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9.6
  - matplotlib
  - pandas
  - numpy
  - scikit-learn
  - jupyterlab
  - seaborn
  - nltk
  - scipy
  - tqdm
  - jupyterlab_widgets
  - ipywidgets
  - nodejs
  - networkx
  - plotly
  - pip
  - pip:
    - rich
